---
name: arborist-action
description: Prune orphaned branches from a forest of repos
inputs:
  repo-token:
    description: "Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}"
    required: false
    default: ${{ github.token }}
runs:
  using: docker
  image: Dockerfile
